# Generated by Django 4.1.1 on 2022-10-13 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactFRM',
            new_name='ContactForm',
        ),
    ]
